/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SetTopBox } from "./SetTopBox";
import { SetTopBoxCountArgs } from "./SetTopBoxCountArgs";
import { SetTopBoxFindManyArgs } from "./SetTopBoxFindManyArgs";
import { SetTopBoxFindUniqueArgs } from "./SetTopBoxFindUniqueArgs";
import { DeleteSetTopBoxArgs } from "./DeleteSetTopBoxArgs";
import { SetTopBoxService } from "../setTopBox.service";
@graphql.Resolver(() => SetTopBox)
export class SetTopBoxResolverBase {
  constructor(protected readonly service: SetTopBoxService) {}

  async _setTopBoxesMeta(
    @graphql.Args() args: SetTopBoxCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SetTopBox])
  async setTopBoxes(
    @graphql.Args() args: SetTopBoxFindManyArgs
  ): Promise<SetTopBox[]> {
    return this.service.setTopBoxes(args);
  }

  @graphql.Query(() => SetTopBox, { nullable: true })
  async setTopBox(
    @graphql.Args() args: SetTopBoxFindUniqueArgs
  ): Promise<SetTopBox | null> {
    const result = await this.service.setTopBox(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SetTopBox)
  async deleteSetTopBox(
    @graphql.Args() args: DeleteSetTopBoxArgs
  ): Promise<SetTopBox | null> {
    try {
      return await this.service.deleteSetTopBox(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
